import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { checkRateLimit, RATE_LIMITS } from '@/lib/rate-limit';

export const maxDuration = 120; // Video extraction can be slow

/**
 * POST /api/generate/video-frames
 * Extract key frames from a YouTube video URL.
 *
 * Accepts: { url: string }
 * Returns: { extractionId, videoTitle, frames: [{ url, timestampSec }] }
 *
 * NOTE: This is a placeholder implementation. Full implementation requires
 * yt-dlp + ffmpeg on the server, which needs a custom Docker deployment
 * (not available in Vercel serverless). For MVP, this uses a still-frame
 * extraction approach via YouTube's thumbnail API.
 */
export async function POST(request: Request) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json(
        { error: 'Unauthorized', code: 'UNAUTHORIZED' },
        { status: 401 }
      );
    }

    // Rate limit: 10 per minute
    const rl = checkRateLimit(`gen:${user.id}`, RATE_LIMITS.generation);
    if (!rl.allowed) {
      return NextResponse.json(
        { error: 'Too many requests. Please wait.', code: 'RATE_LIMITED' },
        { status: 429, headers: { 'Retry-After': String(Math.ceil((rl.resetAt - Date.now()) / 1000)) } }
      );
    }

    // Check pro-tier access
    const { data: profile } = await supabase
      .from('profiles')
      .select('tier, credits_remaining')
      .eq('user_id', user.id)
      .single();

    if (!profile || profile.tier === 'free') {
      return NextResponse.json(
        {
          error: 'Video frame extraction requires a Pro or Enterprise plan',
          code: 'UPGRADE_REQUIRED',
        },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { url } = body;

    if (!url || typeof url !== 'string') {
      return NextResponse.json(
        { error: 'YouTube URL is required', code: 'INVALID_INPUT' },
        { status: 400 }
      );
    }

    // Extract YouTube video ID from various URL formats
    const videoId = extractYouTubeId(url);
    if (!videoId) {
      return NextResponse.json(
        {
          error: 'Invalid YouTube URL. Supported formats: youtube.com/watch?v=..., youtu.be/...',
          code: 'INVALID_INPUT',
        },
        { status: 400 }
      );
    }

    // Fetch video metadata via oEmbed (no API key needed)
    let videoTitle = `YouTube Video ${videoId}`;
    try {
      const oEmbedRes = await fetch(
        `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
      );
      if (oEmbedRes.ok) {
        const meta = await oEmbedRes.json();
        videoTitle = meta.title || videoTitle;
      }
    } catch {
      // oEmbed failed — use fallback title
    }

    // MVP: use YouTube's auto-generated thumbnail endpoints
    // YouTube generates 4 default thumbnails per video
    const frames = [
      {
        url: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
        timestampSec: 0,
      },
      {
        url: `https://img.youtube.com/vi/${videoId}/sddefault.jpg`,
        timestampSec: 0,
      },
      {
        url: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
        timestampSec: 0,
      },
      {
        url: `https://img.youtube.com/vi/${videoId}/mqdefault.jpg`,
        timestampSec: 0,
      },
      // Storyboard frames (auto-generated by YouTube at specific intervals)
      {
        url: `https://img.youtube.com/vi/${videoId}/1.jpg`,
        timestampSec: 25,
      },
      {
        url: `https://img.youtube.com/vi/${videoId}/2.jpg`,
        timestampSec: 50,
      },
      {
        url: `https://img.youtube.com/vi/${videoId}/3.jpg`,
        timestampSec: 75,
      },
    ];

    // Validate which URLs actually resolve (some may 404)
    const validFrames = await filterValidFrames(frames);

    // Save extraction record
    const { data: extraction, error } = await supabase
      .from('video_extractions')
      .insert({
        user_id: user.id,
        youtube_url: url,
        video_title: videoTitle,
        key_frames: validFrames,
        frame_count: validFrames.length,
        status: 'completed',
      })
      .select('id')
      .single();

    if (error || !extraction) {
      console.error('Video extraction save error:', error);
      return NextResponse.json(
        { error: 'Failed to save extraction', code: 'SERVER_ERROR' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      extractionId: extraction.id,
      videoTitle,
      videoId,
      frames: validFrames,
    });
  } catch (error) {
    console.error('Video frames error:', error);
    return NextResponse.json(
      { error: 'Internal server error', code: 'SERVER_ERROR' },
      { status: 500 }
    );
  }
}

/**
 * Extract YouTube video ID from a URL.
 */
function extractYouTubeId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /^([a-zA-Z0-9_-]{11})$/, // Plain video ID
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

/**
 * Filter out frames that return 404.
 */
async function filterValidFrames(
  frames: { url: string; timestampSec: number }[]
): Promise<{ url: string; timestampSec: number }[]> {
  const checks = await Promise.allSettled(
    frames.map(async (frame) => {
      try {
        const res = await fetch(frame.url, { method: 'HEAD' });
        return res.ok ? frame : null;
      } catch {
        return null;
      }
    })
  );

  return checks
    .map((r) => (r.status === 'fulfilled' ? r.value : null))
    .filter((f): f is { url: string; timestampSec: number } => f !== null);
}
